######################## default configuration ####################
baseURL = "https://aviondemand.github.io/conference/"
title = "TGTA Conference"
theme = "avicon"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "avicon" # get your shortname form here: https://disqus.com
# disable language
disableLanguages = [] # disable language from here

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/syotimer/syotimer.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Speakers"
  URL = "speaker"
  weight = 3

  [[menu.main]]
  weight = 4
  name = "Pages"
  hasChildren = true

    [[menu.main]]
    parent = "Pages"
    name = "Tickets"
    URL = "pricing"

#    [[menu.main]]
#    parent = "Pages"
#    name = "Blog"
#    URL = "blog"

    [[menu.main]]
    parent = "Pages"
    name = "Schedule"
    URL = "schedule"

    [[menu.main]]
    parent = "Pages"
    name = "FAQ"
    URL = "faq"
    
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5

#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "Expert Training for the Automotive Professional"
author = "byteskeptical"
# email address
email = "support@aviconference.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analytics_id = ""
# search for blog page
search = false

# Preloader
[params.preloader]
enable = true
preloader = "png" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Register Now"
link = "pricing"


# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "" # replace this url with yours
mailchimp_form_name = "" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "${TEST}"
map_latitude = "20.489113"
map_longitude = "-82.0131468"
map_marker = "images/marker.png"


############################# social icon ############################
[[params.social]]
icon = "tf-ion-social-facebook"
link = "https://www.facebook.com/AVIautomotivevideo/"

[[params.social]]
icon = "tf-ion-social-twitter"
link = "https://twitter.com/automotivevideo"

[[params.social]]
icon = "tf-ion-social-linkedin"
link = "https://www.linkedin.com/company/avi-automotive-video-innovations-llc/"

#[[params.social]]
#icon = "tf-ion-social-pinterest"
#link = "#"

#[[params.social]]
#icon = "tf-ion-social-rss"
#link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# footer content
footer_content = "Send your best technician to premiere hands-on, expert-led training!"
# copyright
copyright = "Powered by AVI"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# footer content
footer_content = "Rejoignez la première entreprise de formation automobile pour une formation sur place dirigée par des experts!"
# copyright
copyright = "Copyright réservé à TGTA Conference"
