name: github pages

on:
  push:
    branches:
      - root
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        env:
          ANALYTICS: ${{ secrets.ANALYTICS }}
          GMAP_API: ${{ secrets.GMAP_API }}
        run: |
          sed -i -e "s|^gmap_api =.*|gmap_api = \"$GMAP_API\"|" -e "s|^google_analytics_id =.*|google_analytics_id = \"$ANALYTICS\"|" config.toml
          hugo --minify
        working-directory: ./site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/root'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/public
