name: github pages

on:
  push:
    branches:
      - root
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          sed -i 's/^gmap_api =.*/gmap_api = "${{ secrets.GMAP_API }}"/g' config.toml
          sed -i 's/^google_analytics_id =.*/google_analytics_id = "${{ secrets.ANALYTICS }}"/g' config.toml
          hugo --minify
        working-directory: ./site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/root'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/public
